# Generated by Django 4.2.24 on 2025-09-13 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_vendor_bank_account_name_vendor_bank_account_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='My Company', max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='client_logos/')),
                ('address', models.TextField(default='')),
                ('email', models.EmailField(default='', max_length=254)),
                ('phone_number', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
