# Generated by Django 5.2.6 on 2025-09-13 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Vendor',
        ),
    ]
